name: ci
on:
  push:
    branches:
      - master
      - 'release-*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.6", "3.7"]
    steps:
      - uses: actions/checkout@v1
      - name: Use Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Commit Lint
        run: |
          gitlint --commits origin/master..
      - name: Format
        run: |
          black . --check --diff
      # disable for now. Should think about using pyright
      # - name: Lint
      #   run: |
      #     pylint data_lake/ tests/
      - name: Import Sorting
        run: |
          isort -rc tests/ data_lake/ migrations/ --check --diff
#      - name: Setup
#        run: |
#          python setup.py install
#      - name: Test
#        run: |
#          pytest -vv
